### ISSUE TITLE
Text scales with resolution, unreadable on large displays

### ISSUE THREAD

**Issue by Dangerdino30** [pkhead/rained#4]
4096x2160
![image](https://github.com/pkhead/rained/assets/77747398/b9569762-95d6-4f04-be8e-443ebadf333b)
1980x1080
![image](https://github.com/pkhead/rained/assets/77747398/67fcec2b-7021-491d-9817-d741fabb5d1a)

**Comment by Dangerdino30** [comment]
It seems to change with my display resolution(If I were to go into settings and adjust my resolution it changes). The text is closer together and larger on small resolution and smaller/further apart on higher resolutions, often unreadably small. My best asumption would be that the size of the text is dependant on pixel size or smth, therefore resoltion size

**Comment by pkhead** [comment]
Sorry it took so long for me to address the issue. I've made it so that it scales the window contents by the monitor's DPI, which I believe should fix this issue. The user may also change the content scale in the preferences window, in case it's not big enough. This should fix the issue, so I will close it.
